apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grocy
components:
  - ../../../components/network-policies/base
  - ../../../components/network-policies/traefik-ingress
  - ../../../components/network-policies/internet-egress
resources:
  - helmrelease.yaml
  - configmap.yaml
  - pvc.yaml
  - ingress.yaml
