apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  interval: 30m
  timeout: 10m
  targetNamespace: kube-system
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "3.4.0"
      sourceRef:
        kind: HelmRepository
        name: aws-load-balancer-controller
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    clusterName: aws-1
    region: eu-central-1
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::867344464550:role/bedrock-eks-aws-load-balancer-controller
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
