apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-autoscaler-source.yaml
  - cluster-autoscaler-helmrelease.yaml
  - aws-load-balancer-controller-source.yaml
  - aws-load-balancer-controller-helmrelease.yaml
  - ../../clusters/home/apps/blog/overlays/eks
