apiVersion: horizon.dev/v1alpha1
kind: ProviderConfig
metadata:
  name: hetzner
spec:
  type: hetzner
  hetzner:
    credentialsSecretRef:
      name: horizon-hetzner
      key: token
    cloudInitSecretRef:
      name: horizon-cloud-init
      key: cloud-init
    nodeCredentialSecretRef:
      name: horizon-hetzner
      key: token
    image:
      selector:
        caph-image-name: bedrock-cluster-node
    joinTokenSecretRef:
      name: horizon-join-token
      key: token
    firewalls:
      - horizon-burst
  watchdog:
    renewInterval: 1m
    slack: 2m
    maxLifetime: 8h
