apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3
  inheritedMetadata:
    labels:
      velero.io/exclude-from-backup: "true"
      recurring-job.longhorn.io/source: enabled
      recurring-job.longhorn.io/snapshot-prune: enabled
      recurring-job.longhorn.io/filesystem-trim: enabled
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  enableSuperuserAccess: true
  priorityClassName: system-cluster-critical
  postgresql:
    parameters:
      max_slot_wal_keep_size: 2GB
    synchronous:
      method: any
      number: 1
      dataDurability: preferred
  storage:
    size: 8Gi
    storageClass: longhorn
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 768Mi
  bootstrap:
    initdb:
      database: app
      owner: app
  managed:
    roles:
      - name: authentik
        login: true
        passwordSecret:
          name: pg-authentik
      - name: paperless
        login: true
        passwordSecret:
          name: pg-paperless
      - name: miniflux
        login: true
        passwordSecret:
          name: pg-miniflux
      - name: open-webui
        login: true
        passwordSecret:
          name: pg-open-webui
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://basalt-cnpg-backups/
      endpointURL: https://hel1.your-objectstorage.com
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-s3
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 2
      data:
        compression: gzip
