apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres-hetzner
  namespace: postgres
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://basalt-cnpg-backups/
    endpointURL: https://hel1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: cnpg-backup-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-backup-s3
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
