apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:yU9IneStCb9XNkrzmdRAvCMK/2YEX1GLD0mK0syl4vN7KT86ZvdJ+AWYwDLHHTd9vGPZeRlHubBjw3/6B64VlB8z/o1CEBmvuY82rybEUoagqlW162jh1shTxWDp2zpu+s2ga2HHdq1eG4CSzFPcd9D2fPl8RPIMFXQ9Dzyz+4NE8rjq6e105W0VsLZmJzDNjPNnI9f0PM32hPpbF4SQw/o=,iv:727Vt+tgD8Ue3RTRcekBSJF0xh6/3oBasrHEkiD5YPE=,tag:fsoTK9L6VQmi9triEB7s1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN1hzenROSmQ1ZGxFRjlo
            VDVUSkdjNXdVRzRZRXQya2w1ZG52L1VaSVVvCnpVUWJTSWFnb2Q5eU1tY3M3UUlZ
            cWk5WWovL0dQQk94cHhHbnE4YmlwOEUKLS0tIEo5Rk96Y1crZE54LzZlUWRlTW1G
            c3dTNjhTdFRIaGtNWUNRRlRib0VmZGMKpEa2z2a2A68b3TbG0UejdxGdZvzv9jLi
            zOFq+mwFfi9go8JGJFyYxInWiHH0b7H+PIZ/vfmJekF+3hTphSeosA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T12:18:39Z"
    mac: ENC[AES256_GCM,data:KthSkrXLWyzWSH64sqszpwsiZFGH6dc7aUwS7MiVaUgTfETEpmnX6bm51T0knEG/pudum6wNKlI+UvE5SZFdZ3ioy4ziBbfKKIL1SOQVnS9mkwib+1fuABo8H+6sMX5lnIgb0SouyFYx6J9eXJnq5keoZ7U76/BGxxTpoBRZI2w=,iv:JGSqlCUEVqqbd7oaLE22EBNH1TD7jPGzMt1Xlt0SjDw=,tag:ywVLmJCYWcWLO0kl7GcT/w==,type:str]
    version: 3.13.1
