apiVersion: v1
kind: Secret
metadata:
    name: tailscale-burst-authkey
    namespace: caph-system
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:BMQnqr6G7+4UzwsA8HmIDhsm9DmNWuQwJk/ObDC7Q11xCRqYAIjkuTVK+/tnU9Mi1L17fKwDSBrJA8IuWA==,iv:JhPnIwB6WAIZ6zidKlZEq1kkojnW+0n9cr9w7M+XOUE=,tag:+tRk5jr9xvnE06BCI/NlPw==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Tjl0QnU5bzZEUmk5WnF0
            UnNVTUpvaGtFS2dLd1U4Z2Q4QTgxVTFRZ2kwCkFPQUJGSFJTc1dFd0oveVJWWTgz
            S2crZ2Z2YW9MSW5wVWw5VVlsZm52RE0KLS0tIFE0T1dnWnprSEljMHBsa0VlbCsv
            TDIwVWV3WDlrV2ZuNnV6ZC9RL29uSmMKQYBt2JzCKz9lEjZeSiToc/N63n2lkhqu
            kMIT0GMCF8U0ugs9urc6QXPe1QnGtDPk6Cw95LZtZJHsn4anTF4y+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T22:04:56Z"
    mac: ENC[AES256_GCM,data:VhkAlKEEQM5yHU2sSU86UyFsmPqStEgEWD0XeOuWyix4XSfFPqPSqqwmrrDJMozQrqdh+jrbf5H6vkC49CzgoB4MLJwchjbPb2/Sqm5SlkXkpBn40R+1i1Iyx/RsGSMwXZEd7YXoWGx8VYjIBzyUYlZIs+J+mMzksZIJYU3wsOA=,iv:rp76n20N2kyou1mWB8wBxn8+NAMiMGbH1q5ZwLzAOOA=,tag:dPLNDMR3GqN8NJcHRHx+ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.1
