apiVersion: v1
kind: Secret
metadata:
    name: tailscale-peer-authkey
    namespace: caph-system
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:c6BuReiXQ3qYUEbRPDAYfFHbRWbiE3j4zxJgQTE=,iv:VnupOMbf2B6XHsB+cl1fM0o9klU1p45X1ocmiH0rLIY=,tag:rDg/OmXokbPxM1gFtdhVHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUzA3R1dBd2RWU1I4TURn
            VEFHYmNuV04yVVZxQ2x4OHFIOG04WFA1akE0CkVRdk1EbG9odTB6NHpRNGs4OW1O
            Y2lNdGdmL1BUTkVTOHRVUWxyeTE3dm8KLS0tIFpOMEIySDA2M3ZPZEdQSmozUXpG
            RlNibnB1bzBXTkZFY3F5Q0pPREI4dncK7bTVGLEwV/Nmipx0qGu70k5otmbfgoyY
            CPVIRMM1PYIKXHg/5DyEaa0C1k1iqLt+aQr2ZPHg4xc31yHuOtOtqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T12:25:37Z"
    mac: ENC[AES256_GCM,data:cKgXiQilYguCz/IEdGNfbXm5z7RsM8N2R7BDjY9r3kWB9XdEOREAnju5hKSO2X9cbK1iz2DcovXgPB595bpPieHviQ7mD5i12epDqxZ+r9OaiRa5mrGbBWOTI+rw0x+I5nc4nOs9UVaitoqgWXpJwEsNd3V1bFBMhNhz3DBWJns=,iv:EgXknOHZqOZUuIn7dmn4JXW4VWCIDqon/mlmESblEyI=,tag:46VnkoGKV+SbPGR2QmcQng==,type:str]
    version: 3.13.1
