apiVersion: v1
kind: Secret
metadata:
    name: tailscale-peer-authkey
    namespace: caph-system
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:e3ENw6c07tnP0IEH+ikMxyqlm50KkmeZHItOHmprbo4PQ8vBAJC2oC1sW/V5IgpsKaDRlwRahwkG00hXIA==,iv:yjiK6cpi6gxrCqcy4MTH2TWdXDRp7b+j34mgk4D8wBg=,tag:sjnKOS1yUNeXXfU96ljWtQ==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUzA3R1dBd2RWU1I4TURn
            VEFHYmNuV04yVVZxQ2x4OHFIOG04WFA1akE0CkVRdk1EbG9odTB6NHpRNGs4OW1O
            Y2lNdGdmL1BUTkVTOHRVUWxyeTE3dm8KLS0tIFpOMEIySDA2M3ZPZEdQSmozUXpG
            RlNibnB1bzBXTkZFY3F5Q0pPREI4dncK7bTVGLEwV/Nmipx0qGu70k5otmbfgoyY
            CPVIRMM1PYIKXHg/5DyEaa0C1k1iqLt+aQr2ZPHg4xc31yHuOtOtqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T12:33:11Z"
    mac: ENC[AES256_GCM,data:qI3p3zFy8Sn91z6lCSQ3b1oYyuUPD97n9scmoZ4ct0y5SolijWBr0nuqwUmYcqkgzkWSG14sTM+QO/wMiGEaKrWU5m674OyA8yzpwlGXvAq7bbZxuaisnq7ygvavkadFZ/3B75Q3/NvsZkTXCPs8ORXQDfa2rbFyE+w2S3Vnfmw=,iv:SW20eZ9ZgMA0iZ7dZP0PqIeSK43U+OfHsa/x+96iAzE=,tag:XrNmVffLUngP4PZcB/Chow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.1
