apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

components:
  - ../../../../components/authentik-middleware

resources:
  - helmrelease.yaml
  - certificate.yaml
  - dashboard-ingress.yaml
  - networkpolicies.yaml
  - pdb.yaml
  - security-headers.yaml
  - tlsoption.yaml

