apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel
components:
  - ../../../../components/network-policies/internet-egress
resources:
  - config.yaml
  - helmrelease.yaml
  - networkpolicies.yaml
  - pdb.yaml
patches:
  - target:
      kind: NetworkPolicy
      name: allow-internet-egress
    patch: |-
      - op: add
        path: /spec/egress/0/ports/-
        value:
          protocol: UDP
          port: 7844
      - op: add
        path: /spec/egress/0/ports/-
        value:
          protocol: TCP
          port: 7844
