apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: n8n
  namespace: n8n
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: n8n
      app.kubernetes.io/name: n8n
