apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KThreesConfigTemplate
metadata:
  name: elastic
  namespace: caph-system
spec:
  template:
    spec:
      agentConfig:
        airGapped: true
        nodeLabels:
          - horizon.dev/pool=elastic
      files:
        - path: /etc/tailscale/authkey
          owner: root:root
          permissions: "0400"
          contentFrom:
            secret:
              name: tailscale-burst-authkey
              key: authkey
