apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml
  - hetznercluster.yaml
  - hcloudmachinetemplate-worker.yaml
  - kthreesconfigtemplate-elastic.yaml
  - kthreesconfigtemplate-reserved.yaml
  - machinedeployment-elastic.yaml
  - machinedeployment-reserved.yaml
