apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: elastic-workers
  namespace: caph-system
  labels:
    cluster.x-k8s.io/cluster-name: burst
    horizon.dev/managed-by: horizon
    horizon.dev/pool-type: elastic
    horizon.dev/pool-name: elastic-workers
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "0"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "2"
spec:
  clusterName: burst
  selector:
    matchLabels:
      horizon.dev/managed-by: horizon
      horizon.dev/pool-name: elastic-workers
  template:
    metadata:
      labels:
        horizon.dev/managed-by: horizon
        horizon.dev/pool-type: elastic
        horizon.dev/pool-name: elastic-workers
    spec:
      clusterName: burst
      version: v1.35.2+k3s1
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KThreesConfigTemplate
          name: elastic
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: HCloudMachineTemplate
        name: worker
