apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ntfy-ingress
  namespace: ntfy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ntfy
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ntfy-egress
  namespace: ntfy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ntfy
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.42.0.0/16
              - 10.43.0.0/16
      ports:
        - protocol: TCP
          port: 443
