---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: blog
  namespace: flux-system
spec:
  image: ghcr.io/lucawalz/blog
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: blog
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog
  filterTags:
    pattern: '^main-(?P<ts>[0-9]+)-[0-9a-f]+$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: blog
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: "chore(blog): update image to newest build"
    push:
      branch: main
  update:
    path: ./kubernetes/clusters/home/apps/blog
    strategy: Setters
