apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-init
    namespace: postgres
type: Opaque
stringData:
    authentik-db-password: ENC[AES256_GCM,data:FaWrfW9n5EBLTQqhIYhLn/UwRj/+0Hp7RWb7kR948+A=,iv:SXw0PcEj3vspl5jDLhhFdsaf+g/ufoupFVKsEy9MKPQ=,tag:28SINg41Bghjm2dBNrKOWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS2wxTEZiV2xhcVB5enh1
            TjdkaUNESytaRk1DdTNOV2xacmZaUmdhT3dFCmIxN0MrdVRnVE9BY1l0ZW9LTm4x
            byt2TjRoZFNRdFpnSkdoZE8xRHhGWEUKLS0tIDVDbHJ6ajY2RDA1L2VoTUhZMzFI
            QlVNS1NCeWRvUFlsckFIZmp3djQrVmcKxA6Q2QbHiSAJFXtwmGMcg6O9824AgSbC
            MFBzf4V4OVOVNdK8M80viRH82kRuJTxAZxYsKJnsvP9K3RvGThhWlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T23:00:28Z"
    mac: ENC[AES256_GCM,data:B81dKi/DxqlETaZFWKFOWHpmft783cxAuMUiia1yKNBt/wID2RY4UgcrodWBAVXtp31PAWg00f3iMzZ/hOazyw120AGy48yzTU61pDoEhUIyRiIRzBzVLbGuGtm/EKUbWGSQJU5VXh/c/qIvQJC9QbVQlHv9v9HoiFxykF1QWcM=,iv:g6mf9mW7Obcl7oolJdFcZsxzZ6Q0ZUArOAlNQtyXbvM=,tag:AeRSKfGJFHEZMd345GmBtw==,type:str]
    version: 3.13.1
