apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: authentik
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:lhA9lwY1iOQk0yTyLvxQytXYQDoYSkMZbrm0pNw+xMfgOhl0j8otNOJth5RCkBG+UUGANDvBIzOE52S4,iv:WwgaHY8354xVSlnNN1U4lgvhmnjYapY7uaM8ulzVa4s=,tag:aekrpVaTpqvMq/z+P5eATg==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:saYGU/Tetf6x7sJxtKAFgn9I6+FF2XTv55sAdaTLffo=,iv:g4IcYdbfQWR2v50hv2B2xicJxAkTr6E8xiqpBHBBizM=,tag:iqyqtdI8HVo0m/DsdAqKGQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:PuNrf+edOe9p+JIHPJ27mdnrBCZHvMiSbaxXZShgV98=,iv:yI0843ABT1iTpMiCnEfYWuQVqpF/9/mIfidCkpAyZ+8=,tag:YU1ya2Y7wNzGOyHJk3QAxg==,type:str]
    github-client-id: ENC[AES256_GCM,data:XpGYkwXH/X3Cuj52WtsWMLZQiDWh3GcO1ixyIKSnnP79bG+HKtiS,iv:uSzzT35AHRNHJVS9UCY3s4snNYA73o0JX6kN9JSck3E=,tag:pOy2ZYKkw/74ZjtW+qZZRQ==,type:str]
    github-client-secret: ENC[AES256_GCM,data:8aM3GJub6TrvRFudAgo+SXRbUomEi33Qvj8teWGcC8IdETiSNFYlxMozIw==,iv:9pMPssXlVXTHBZ9QU9DKXc4aNhS66G9svrlWrt3uaMY=,tag:KbeFkpmeBNYeyQTs0i4I4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeTlKSVlSZHZuSm9TSlVM
            dndQbUc4MEpyR2FoTUlDQ0NiUHNLeEViSldRCk4zQWljZzZzUmw5cG95T2dCa1BE
            M3JIZXF1aUtVV1hVaElzZnVFbjRXWGMKLS0tIDZwWDRqWk0vdnZRMWlET3NiUjdy
            V0JyM250V3NhK1phRTFvMlRoK0dTUGcKDrdtIaeX2aZ220hOr7wBsbdOvwhQ2w0q
            awHSqBXgMy4KqiuqSlW7YcgVtQXqG3y3c/7LOrYYFU2qat0GF8xQug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T23:00:27Z"
    mac: ENC[AES256_GCM,data:IGaNKgU4ATnZ6W+i8V1LWGmbygwCVf2dgs6O0Ui9gGdwG3IBcLMrSAJ7wGdIs+VlxiurF283EpRNr6eXZ8/1/j0g5dLA+OLP4Hcn4yoUHuTjAZOe9cRozsdUBaKdBuKj1qccdF83oiVbKUAKSoRRCRL1eP/sXjkzAWLmJCXHAwI=,iv:tHSRlmBr2Fm/Fd9A1v5ZDCC3qhG+LS/L3nxzMH8yi0w=,tag:aWmyCLQVGP06gZ4rLmfSkA==,type:str]
    version: 3.13.1
