apiVersion: v1
kind: Secret
metadata:
    name: hetzner
    namespace: caph-system
type: Opaque
stringData:
    hcloud-token: ENC[AES256_GCM,data:jgGDn+OVptgYTjGKMjN0a++ddpBkbYWysb5xu1U=,iv:AkGAjLcR54zEnivOYbq+L0s58fumDoqLm/gwTU0lcas=,tag:oj6gV4OR2mMB+2wBF21G6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS0ZFMnZQbmZmU2FjTXNQ
            a2xNUjZPVGdMYWVYUmV2M1ZtdjhSbjU0R20wCmk5YW5ZYXRaMWtMNHQ4SkJxTUhM
            MCtyeVBJbnYvS1dUWDV5R0xBWkdGTTAKLS0tIE5RUGdPS0dLUnNneExPU3pINjQ5
            YXNWK0h6ZE9GRlRvMjhnamd6Ky8yWU0KLHb6ZATRV6IE8YOn47w1ta2qOYMocUtP
            kIdcoVcaSGddtVykhkWQVLRTZWdLdFwygsaaJoModCbluwt4LjZNgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T19:43:17Z"
    mac: ENC[AES256_GCM,data:IKKnwu+8J+TcdGZ2S0aHa+rKGvHbS/9ju0G0wYU0E5bU58p6vwckf+8yC0xSGIFV6UN1m+x2bt9YWcckkhLIlH4h+zRMP1hGsNDhFjcK7CFjrVpCWq7crBoMRp0yDA77JSm9Yue+M8JjN0lrv2jgvHVPgnNNhOayL4RLtGDv7zQ=,iv:dtxWlaiRX8869soIP9tSIbu2cOrRzCr+DNIo5gcyIXk=,tag:5+HekaL65d8nHEmdUziphQ==,type:str]
    version: 3.13.1
