apiVersion: v1
kind: Secret
metadata:
    name: aws
    namespace: capa-system
type: Opaque
stringData:
    AWS_B64ENCODED_CREDENTIALS: ENC[AES256_GCM,data:hsr3SqPDVqx33KYq3lX/LUfcwLAt5XKeHS9jblrvlB07qUu4kyM6jNxNavWqJZcFJEiwgf7l4j+eAtf52087KU/UyMed8IOcbxF4Yu8QHXvkmYhZGcVfn/kA+JTuH9dN1cjU/PitUINC1Jum/P8/K/YMjZDIAbD0wenuT+WXeEJhLSPjGxlwoa56MXi4ccnwpnjl9VO4r7xX3xe4/6AIPu/4wh14DmvywmY1Y5LQouE2+hN8,iv:/er3hjDg7VJ8p7qD2C/EEDNv1V/D1LLHAAEwHQo6L58=,tag:Mj/diqABEn64FLYenKrnYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1enRha1RkUndwMmNQUTVw
            c3lVWmZwZXF6enpWUDAxTktXVktzaVIrVlFBCnlLcFQ5cThEamdwejEyMFhST0xF
            MFBJaXYyR0YxYXkzVUdJZ1lBdjl2ZzgKLS0tIG52aEJQOU9OWmhWM1puNDhUVVFo
            VjNwTXM1R3IzZ2RsaDBHenNEcERpaFEKupY2sz07SyuiDad2+AnXL6saLKIgucN0
            RdMQ9jruovO9W6e9z6Z+EEyJczuDDoBzewSzFwbWioTgmVogwVq61g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T17:45:41Z"
    mac: ENC[AES256_GCM,data:dY1dtaO/8Gs0XRHsvx9gc1+ho/l4Etv7zYfUGg+ooei8V5h2pTU1KIK+t2ZRxkDFQcQGmGFSwCkXiwXoesxuAjeFx9WzH3vObspYkxUs+Dm1KoKO+e+1TObz2bI2F9S3U5FjZkKlpJJFQnwbvQJ4V2ICczQyPPi8tnTw9wVbfos=,iv:yFSOXzr551Pd4kyTajbrvibad+lzmVhijJdkvCnJ1dI=,tag:sAhmkZ7FVesjqCwT7gQ15g==,type:str]
    version: 3.13.1
