apiVersion: v1
kind: Secret
metadata:
    name: hetzner
    namespace: caph-system
type: Opaque
stringData:
    hcloud-token: ENC[AES256_GCM,data:2Dy24cghz0xtfZ0KA9/vHnq1Dxp3h2Ke8EAuc8JssXGHp5OiejR86D6QyQRSOfs9oNpQ9Ecti3iUWn2k+LM38g==,iv:p9M5vxLEBQ67S5gLQ14aztCMFrXpX+eh95YbN/6bNFU=,tag:F45VmMV+s5Rv02gcFLIXWw==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS0ZFMnZQbmZmU2FjTXNQ
            a2xNUjZPVGdMYWVYUmV2M1ZtdjhSbjU0R20wCmk5YW5ZYXRaMWtMNHQ4SkJxTUhM
            MCtyeVBJbnYvS1dUWDV5R0xBWkdGTTAKLS0tIE5RUGdPS0dLUnNneExPU3pINjQ5
            YXNWK0h6ZE9GRlRvMjhnamd6Ky8yWU0KLHb6ZATRV6IE8YOn47w1ta2qOYMocUtP
            kIdcoVcaSGddtVykhkWQVLRTZWdLdFwygsaaJoModCbluwt4LjZNgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T23:56:49Z"
    mac: ENC[AES256_GCM,data:a83KUKmCHrFIfV566LFlwfFUUdIh1WcOis4b1bfITk7jZgk5iwJcTuYQAm0CtY+ErBRvfFUeIVbLkDj2uUefJQycok5RtILoE+O++4sURccEoSs1QsRPvfDOEaBV+MKzdIdq1+Ll0A7cOkA9/sSLSIyvyg0ArmZQlSNnrPaZqNA=,iv:DqH5jNUWfLS4OMAg73ENbDksIvEXugv3NCASAcdB6M8=,tag:O2B+MuwzYhb5EF9mCimnKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.1
