apiVersion: v1
kind: Secret
metadata:
    name: ghcr-imagepull
    namespace: caph-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:qbwd4zp++Vwm5QCxBaAhTT3gHlOE8GMuciU2A2MAiku6pkwsAkPBDDPDkw7ufuJQZNj4kj0dxIbvHATmcOHflOLcNVr8CQ21tZOMFzq3iV5KdROak2UT2/YChnxi//GzGAtCTAN0hV9sCqCcPm9Mk54Ql6Ns4gGUWfuxXA2M8lmBJ3LDPD9XbG6nOxbdKkydlE0anSpvBNqb6zBtcZ5eTnLc3qgfNRFFxrslQO+5OSdH,iv:SRRTLF1lgSFqdoKWAD6XilFKwXMKIqIW/+7Be7+KrBc=,tag:IIldpi/l6U5pjJY+1MaVFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQmJkZzRUTWRMdWpoQVRM
            WEZ6R1VvVytPNTVBaVFYRjhMRm9VWWFzNFE0CmtlZ2g5dWlQd2JLTjhObGZ2eWdr
            a1VoUDByeHZoZ1l1SitEbGxnT1VydEEKLS0tIFB4QitNTjRGNHp3d0dHUTMvSU5r
            dzJXMTRCdGJGaGZDenhvWHRrUFFzYXcKjYE0xHS8inJMMMBP3w4maMl83HMzRN/2
            K3o+VEkYC+ChaUXfDZ3hLrUT6I3KskGBcfMFo33ZyM21cTISHm2VZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T14:26:09Z"
    mac: ENC[AES256_GCM,data:eJQc9RSMgRC9w3QybcOP+eDTk1qgBezqHTRQjE8y2PEE2IR2mRhkH0nDR95obYj0iOsxDAqXxyfJnzDj/Cjv6Xu7BiQM31Jq6PrMhVAKXtJB+M+8gHHT1tnaobd7ZIZgWnKjCoql+n2TeI2x0wlnLQ1rrzBCpLikq0gXl7AGUwA=,iv:WXrPBUaNgDkzTJaWVFlFdT7l9kK5UeIb/cuB9S5lNmE=,tag:FKfD0Y0XZ2CZXKNAIFg2LQ==,type:str]
    version: 3.13.1
