apiVersion: v1
kind: Secret
metadata:
    name: velero-ui-passphrase
    namespace: velero
type: Opaque
stringData:
    pass_phrase: ENC[AES256_GCM,data:ws3YU86ty6TafcQCJNwoSGpb9Q9gE43gZg7IFSFqA6K4IYqy2IWvnl5eFeBWN+AJkVMoz74CfSeKJhcCuK1MUg==,iv:EBh6pb9ntjXCb3cVmndwrGKB0p6DyeofloOXfHoKBRY=,tag:Gu/Lf2Nq3hM9K+dMvPL8rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTEQ0SHVQTmhpLzI4U0U5
            eEpzTDMyalkzaHJxYUVCWVNhZHpoSVNMVUgwCnNtWHVxWG5vUTgxTEhhVys1eFl0
            R3JmRDM2WGFPY3lFcGJETENiQjN0a28KLS0tIHdJelJUME56d0d0OGR4YmJUcDdX
            Y25yYnhKOFVES0h2T2xNTWNMenlmekEKB+qyXsfTbOGCo1O6IUXs+q6whJUvQ358
            JH4wPpUA9TBfvTPjIP2p7OZ0d+TjjliuuJlOiTjlQc5Ff9JJmJluSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T20:20:02Z"
    mac: ENC[AES256_GCM,data:bQhYSur7li4JZEhRDT2laRBHWbZLPIcg5J62anbNnp2co4EUYCxM5wGvGvlJZGxeq5MZr8Dit6TCNfyaAbR7JQ4eebUn8a1eRHR31XckAQMh5TVwznCLOdo5XjF2atZTHsjR/5L5qIQg1kvBs1a4cZN8OG8QjuDk+s3zCMmgqus=,iv:ivzZU5PwmKLaNQ0ryU9x7rN+UZSDQb+SecnDqLkAaQk=,tag:+8tUHreesAw14ih2dJYGiw==,type:str]
    version: 3.13.1
