apiVersion: v1
kind: Secret
metadata:
    name: velero-ui-auth
    namespace: velero
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ruApQnM=,iv:XkAy2OI0oBOrhrA4MLKn2NDqo0F4VJ9UJv6gIfZF4X8=,tag:GUOqGFB8X0Epn2qs3Lk0Yg==,type:str]
    password: ENC[AES256_GCM,data:C8vFpyD7fZsdrDN45SiFMZR5eoCaL6AFlhLtYg==,iv:W0ZYUqlgZvl29Df6bZPZtECPff/XSE8h8xu7FQDtNwg=,tag:6PyuTiKyjBpPIJeXi2FYVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSE1oQUJXRE44bTZ1b1cr
            b3U1NnU2OTVHejFRM3B6WHdQRU1tWkdhbWt3CmJab2d0QVF6MXlyR3JZUlpFODVV
            TTN6QWRoUVNJLzVsbVc2UG9va1pvVkEKLS0tIHBpajUrYmJqd0hIU0ZLNE9zazl6
            OE0zTkZZZlE2YmdPQStDOEs0S21SM1EKYtVAocDz07rsbXhLAeCNvDi5suIbE0AR
            IwD24lO0KfAFj0R4S6kNCzbgUXluYZase05+HffPCDJqEYxgRMMjHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T10:49:25Z"
    mac: ENC[AES256_GCM,data:vD0jvD9V7fnMosM9lAJ+9c1S+RfbArGMOBbpI7kIlI1WA538Yzbq8AmvhOw41xjJUm18ZfNiV+579OCv0T9kl7MleiYLUuamoykYhiC5MiLhzx9trvN6i0TM2gDTxh5/KZIpf6wnACl4ppSAX1y0MAMfvxZdGsHy4BbrX8Tv5b8=,iv:pNDMZhokbsthpZRVD6q/BB3yBg4yGgE73ahBWFgLCfg=,tag:BQHCqMmjLzHMVF+94EJ5FA==,type:str]
    version: 3.13.1
