apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
    traefik: true

  settings.yaml: |
    title: syslabs
    theme: dark
    color: slate
    headerStyle: clean
    target: _blank
    useEqualHeights: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: false
      provider: duckduckgo
    layout:
      Apps:
        style: row
        columns: 4
      AI:
        style: row
        columns: 2
      Documents:
        style: row
        columns: 3
      Observability:
        style: row
        columns: 4
      Storage:
        style: row
        columns: 2
      Platform:
        style: row
        columns: 3
      Network:
        style: row
        columns: 2

  docker.yaml: ""

  custom.css: ""

  custom.js: ""

  bookmarks.yaml: |
    - Cluster:
        - Rancher:
            - icon: rancher.png
              href: https://rancher.${cluster_domain}
        - Grafana:
            - icon: grafana.png
              href: https://grafana.${cluster_domain}
    - Cluster ops:
        - Rancher Cluster Management:
            - icon: rancher.png
              href: https://rancher.${cluster_domain}/dashboard/c/local/manager/provisioning.cattle.io.cluster
        - bedrock:
            - icon: github.png
              href: https://github.com/lucawalz/bedrock
        - horizon:
            - icon: github.png
              href: https://github.com/lucawalz/horizon

  services.yaml: |
    - Network:
        - AdGuard Home:
            icon: adguard-home.png
            href: http://10.20.0.1:3000

  widgets.yaml: |
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: cluster
        nodes:
          show: false
    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
