apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
components:
  - ../../../components/network-policies/base
  - ../../../components/network-policies/traefik-ingress
  - ../../../components/authentik-middleware
resources:
  - helmrelease.yaml
  - configmap.yaml
  - rbac.yaml
  - ingress.yaml
  - networkpolicies.yaml
