apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-resources.yaml
  - require-run-as-non-root.yaml
  - disallow-privilege-escalation.yaml
  - require-drop-all-capabilities.yaml
  - disallow-latest-tag.yaml
