apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack-pushgateway
  interval: 30m
  chart:
    spec:
      chart: prometheus-pushgateway
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
      honorLabels: true
    service:
      type: ClusterIP
      port: 9091
    persistentVolume:
      enabled: false
