apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm
components:
  - ../../../components/network-policies/base
resources:
  - ollama
  - ollama-vision
  - open-webui
  - networkpolicies.yaml
