apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: blog
  namespace: blog
spec:
  provider: traefik
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog
  progressDeadlineSeconds: 300
  service:
    port: 80
    targetPort: http
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
