apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kiwix
components:
  - ../../../components/network-policies/base
  - ../../../components/network-policies/traefik-ingress
  - ../../../components/network-policies/internet-egress
  - ../../../components/authentik-middleware
resources:
  - helmrelease.yaml
  - pvc.yaml
  - ingress.yaml
