apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: eks-example
  namespace: capa-system
  labels:
    bedrock.io/gitops-peer: "true"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: AWSManagedControlPlane
    name: eks-example-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: AWSManagedCluster
    name: eks-example
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: eks-example
  namespace: capa-system
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: eks-example-control-plane
  namespace: capa-system
spec:
  region: us-east-1
  sshKeyName: REPLACE-ME
  version: v1.30
  eksClusterName: eks-example
