apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: preferred
  enableSuperuserAccess: true
  storage:
    size: 8Gi
    storageClass: longhorn
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 768Mi
  bootstrap:
    initdb:
      database: app
      owner: app
  managed:
    roles:
      - name: authentik
        login: true
        passwordSecret:
          name: pg-authentik
