---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-edge-onprem
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infrastructure/profiles/edge-onprem
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-sources
    - name: cluster-secrets
    - name: cluster-namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-metallb
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infrastructure/profiles/edge-onprem/metallb/config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-edge-onprem
    - name: cluster-namespaces
