---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-capi-providers
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/fleet/cluster-api/providers
  prune: true
  wait: true
  timeout: 8m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-namespaces
    - name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-capi
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/fleet/cluster-api/cluster-class
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-capi-providers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-fleet
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/fleet/cluster-api/peers
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-capi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-rancher
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/fleet/rancher
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-sources
    - name: cluster-secrets
    - name: cluster-namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-observability
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/fleet/observability
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-sources
    - name: cluster-secrets
    - name: cluster-namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-flux-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/fleet/flux-operator/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-sources
    - name: cluster-namespaces
