---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-rancher
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infrastructure/controllers/rancher
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-sources
    - name: cluster-secrets
    - name: cluster-namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-observability
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infrastructure/controllers/observability
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-sources
    - name: cluster-secrets
    - name: cluster-namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-flux-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infrastructure/controllers/flux-operator
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-sources
    - name: cluster-namespaces
