apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: aws
  namespace: capa-system
spec:
  name: aws
  type: infrastructure
  version: v2.11.1
  configSecret:
    name: aws
  fetchConfig:
    url: https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.11.1/infrastructure-components.yaml
  variables:
    CAPA_EKS: "true"
    CAPA_EKS_IAM: "true"
    EXP_MACHINE_POOL: "true"
