apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: hetzner
  namespace: caph-system
spec:
  name: hetzner
  type: infrastructure
  version: v1.1.6
  configSecret:
    name: hetzner
  fetchConfig:
    url: https://github.com/syself/cluster-api-provider-hetzner/releases
