---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bedrock-secrets
  namespace: flux-system
spec:
  interval: 10m
  url: ssh://git@github.com/lucawalz/bedrock-secrets
  ref:
    branch: main
  secretRef:
    name: bedrock-secrets-git-auth
