apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm/traefik.yaml
  - helm/metallb.yaml
  - helm/bjw-s.yaml
  - helm/n8n.yaml
  - helm/cert-manager.yaml
  - helm/longhorn.yaml
  - helm/prometheus-community.yaml
  - helm/grafana.yaml
  - helm/bitnami.yaml
  - helm/rancher.yaml
  - helm/velero.yaml
  - helm/ollama.yaml
  - helm/open-webui.yaml
  - helm/litellm.yaml
  - helm/pgadmin.yaml
  - helm/stakater.yaml
  - helm/cluster-autoscaler.yaml
  - helm/wrenix.yaml
  - helm/otwld.yaml
  - helm/goauthentik.yaml
  - helm/controlplane.yaml
