apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KThreesControlPlaneTemplate
metadata:
  name: default-control-plane
  namespace: caph-system
spec:
  template:
    spec:
      kthreesConfigSpec:
        serverConfig:
          disableComponents:
            - servicelb
            - traefik
        agentConfig:
          airGapped: true
