apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: aws-1
  namespace: capa-system
  labels:
    bedrock.io/gitops-peer: "true"
    cluster-api.cattle.io/rancher-auto-import: "true"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: AWSManagedControlPlane
    name: aws-1-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: AWSManagedCluster
    name: aws-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: aws-1
  namespace: capa-system
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: aws-1-control-plane
  namespace: capa-system
spec:
  region: eu-central-1
  roleName: eks-controlplane.cluster-api-provider-aws.sigs.k8s.io
  version: v1.33
  eksClusterName: aws-1
  associateOIDCProvider: true
  accessConfig:
    authenticationMode: api_and_config_map
  addons:
    - name: vpc-cni
      version: v1.21.2-eksbuild.2
      conflictResolution: overwrite
    - name: coredns
      version: v1.12.4-eksbuild.17
      conflictResolution: overwrite
    - name: kube-proxy
      version: v1.33.10-eksbuild.11
      conflictResolution: overwrite
    - name: eks-pod-identity-agent
      version: v1.3.10-eksbuild.3
      conflictResolution: overwrite
