apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
components:
  - ../../../components/network-policies/base
resources:
  - paperless-ngx
  - redis
  - gotenberg
  - tika
  - paperless-ai
  - ingress.yaml
  - networkpolicies.yaml
