apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: flagger
      version: "1.44.0"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    meshProvider: traefik
    metricsServer: http://kube-prometheus-stack-prometheus.monitoring:9090
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
    securityContext:
      enabled: true
      context:
        runAsNonRoot: true
        runAsUser: 10001
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
    podMonitor:
      enabled: false
    prometheus:
      install: false
