apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

components:
  - ../../../components/network-policies/internet-egress

resources:
  - helmrelease.yaml
  - redis.yaml
  - blueprints-configmap.yaml
  - ingress.yaml
  - networkpolicies.yaml
  - pdb.yaml

patches:
  - target:
      kind: NetworkPolicy
      name: allow-internet-egress
    patch: |-
      - op: replace
        path: /spec/podSelector
        value:
          matchLabels:
            app.kubernetes.io/name: authentik
