apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3
    namespace: postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:S+swSPt4e+L4FxzWXpgw4gOs1MA=,iv:23g3LvCZXYuU/aTMlI1FzSUN5jrbo/RZPuUuh9M46fE=,tag:/tRO1PjB4bX9m/Ik8qNoHg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:uKr/BAQ+GmgOkoi+GoX5xcCdCWmyrXBAiO7YeOPgTaIExHboCsbn3A==,iv:xDgsh1RKbFB9rwZzSGBLNuMY8bQNvDk/AnB4BJzy8Yo=,tag:EnA5INBt4U6fWRMIZ2IIgQ==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1STRBdjZnQitHdkZJV1p5
            ZzBuMWtvaUM4VnYydW50V0FaMVplSnpxZlI0CjR4MkxMZG05ZTd6ajJ4SCtGd3BK
            ZW9ic01BOEZmWWQ2bXBQajJudEhhR3cKLS0tIDVRYXptdW9hT0hqeVRUUk56a29W
            TDhmR3NncERWa3JpeUkzTVhGdkxPbDAKw1fRPtpbKti1W706EVTonfEzvoeziwqT
            tRuloPZdmOZo1lzMSjcV488EvwpYtqW2O8PfM4lOYAW2Tdai9NAUag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T10:52:38Z"
    mac: ENC[AES256_GCM,data:MyvrSAs5Xqx3+1YQtd8VeXdh/JNgkrqRoFzHGRH+85FDdWejuP9UU9pIbaa9BelclpsRqIbNSiVxZYGhRl8Nwx1fHQx87uLDgMfhTTC/62NSkoRs+zL38RaAK6CAjlTFKQ5fJgA6BuPlHMMMRSFeV+Fenc5ADlnn2rDm8O+uquA=,iv:4N0mnJp6vOUNlkdwW1GHcja2EShOoLMEjG/rMSZbJJo=,tag:hFhkFoDl/i+6EQeYcUDdbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
