apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:QGlWxNo=,iv:Ze17c8juipsItq+n5s3WmU2zhUrHBTxMdgq147PWI58=,tag:4j96eEpF3hM70VENl8ApRw==,type:str]
    admin-password: ENC[AES256_GCM,data:P7oUSj468KIs4XT2T752eYfUYsa3aFOJn7icu7QGzMA=,iv:y89r5GA8l7pi99PRm0iQCo10X09ITwOZq5YGkvgrWYc=,tag:CJ9S+qK/3upGKLOCY5c4sQ==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4a0ZPTm11amhxaEJhZmZD
            THM4MU16Kzd5VGdnQjkrRi9KSklCVmVnUm1zCnBkR21SRkhJQWRkYUgrU25nV1ZT
            NmZTMUdoVXNEUVl0a3BLV2hyR3FKYzQKLS0tIDFkTlZwNjVJV3RmN0RhWGMzT25m
            cmltNXY5bDE2bm5rd2JVOEpvdnp0b2sKmmfUFczTiu2ByobnSmaAWgytUUNT2e3P
            UMtzdOW79Ldct8RfKVX/3TeguNqBLGvE1BeTLgzFKSmpXXetwUuEMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T00:00:42Z"
    mac: ENC[AES256_GCM,data:hT6WJEiBLOjMzXDFh1ZNX0Sd8XYGssC6dCtmnhPbKJ8Fw026za6sBAJP8hQWdJq4eojgeYnM4RknfqxkqWPE/ChTIq4y8adNnlxCYdj9d/Sq7irYY4Xj19lvOyc6sIGX9DSG+mVFX5R4J4mRTyZq5sQmEUO/Nj/fdo0lqCxXcME=,iv:FT02AoYmYUT0+K63lrQ9or3c4e7XrC2n+q6NQW/yHzI=,tag:iHvUf6pFwvycUpbVllv2Og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
