apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana.sops.yaml
  - pgadmin.sops.yaml
  - rancher.sops.yaml
  - pg-authentik.sops.yaml
  - pg-paperless.sops.yaml
  - paperless.sops.yaml
  - velero-ui-auth.sops.yaml
  - velero-ui-passphrase.sops.yaml
  - velero-s3.sops.yaml
  - velero-repo.sops.yaml
  - longhorn-backup.sops.yaml
  - cnpg-backup-s3.sops.yaml
  - minio.sops.yaml
