apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-admin.sops.yaml
  - pgadmin.sops.yaml
  - rancher.sops.yaml
  - litellm.sops.yaml
  - litellm-db-init.sops.yaml
  - velero-ui-auth.sops.yaml
  - velero-ui-passphrase.sops.yaml
  - velero-s3.sops.yaml
  - velero-repo.sops.yaml
  - longhorn-backup.sops.yaml
