apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: llm
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:wG+hqoJjouUQjcACCt4BtAMfzXMK+V8WZzHRr/FYEn/CagpqyUJQj3jtuqkedCcEp6uB9qVIa74z7bEsoT82O/1+LnRF7cV7nvnpzHCq0QtKXQpfDOBK5KIRiBo2fJb71RDU6rsle2f/jNmxKGeP+Yc=,iv:H9T4CSAkBsmn73LiPzjIHQQUpkfH+4ZK4AqpD7BhOE8=,tag:RVEcorIXxPa54PK1ST0HIg==,type:str]
    PROXY_MASTER_KEY: ENC[AES256_GCM,data:m5yG94dtLwfBH9zPWPb0RuY14+uJ1xaaFDRL7a6pvjftn4i58GqagBDWtmb6DD8NECff,iv:wjgYNlobn9n4nN77JUSwy3kKGNS9EbuSOy4eDVCjUHk=,tag:XQtzL7OdMn34UTlrWBQB/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTHk0bVoveFFhOVBDeGcz
            Y0tpTlp2OTJqb0NKRkdtNElvTFNUYWx4K1U4ClQxU0QxYjdSUGY5SUUzL3BrU0w5
            bkNXSUxJbnQzYXdSa1NyVlk5QTMzanMKLS0tIDhERUI3V1J3NmgxMVN5ZkdKRm11
            QkxienhienJNYk5ib3pCaTlzamtzSkUKFNjnsB0/TKJwbxBdqMfT4ABkTK2CGUMT
            NI4O4K+ffD2Yg0UGK4m+TkAC5VF4MfUEBapy04MwhS+I092yYBqAww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T20:19:10Z"
    mac: ENC[AES256_GCM,data:sIUMqeZrvRd3t/ld0qNt0VP99cqccLj28Q1IDKDFD1KX7jLoZG6hxbqZv6dHo1adSQKsTAQ+pY3dcgTm4AKn5rGNVvoFKWij8lP6F7Vx6S7MSg/nQDna1IScVz7X5v2Cui0gl6BywWH1K2jCzOpxTGf2V/nlYr/5KeVRAjw9TpI=,iv:Xsa1yz6D8/WqmWZPiKlij4gGypHFbGgH8FWf8KeFi0E=,tag:KvN9BjDotMPbwN1JLWU+xw==,type:str]
    version: 3.13.1
