apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-credentials
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JAvfDaMnHylfFTQ5tqM9F86H7Lg=,iv:9gMidHWsaANR1qo+MWlL5S9PS2zNFul4b7e9HnFRrR8=,tag:R6efIZGp0uWbNbGXEvDQLA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qyOlGYlzJjbKRXrf8FDVbDo4zkVuo8G5HVTVeaBQfdjy2JpSPivgTQ==,iv:Xf+OLV4/0g2UglCKGB3LF6LuN6IvJuu+hLRswmulMUI=,tag:5jV52OywFYjpatxQvTpDKg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Q2xzaj4sGTe/iys+9DkFJYHEsj4vNGu3IB4E01Vu3H0WG2Y=,iv:KVJaInAwN0Pe6KZyWg/U2f/hMfP6oV51kpe5QqfhJy8=,tag:0p8olCDkkR/Hsd3cUh1GNg==,type:str]
sops:
    age:
        - recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYnY3QlB3UkRBVDZsSW0w
            NlcyU2VONzMrTHpXa2tleURjSXZmcTNBQUZnCjhhRXFBSGYvZyswZXVDVXRLbXFq
            WVR3VDR3N1lvZEtyV2VCNEFzR2I1aTAKLS0tIEVsUXNNa1ByM2hOdXRVM2oxbEpn
            Q001S2YyVmd1dDVEY0hzMGwwRTRENnMKWm+Mfv+DIq1a/4Fc8H80IQILPoqVGoF7
            VgDii1DuXJpBic4/QPH/yvC911tJ67nN3BNCfurijAgWuQejVqF1Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T22:46:08Z"
    mac: ENC[AES256_GCM,data:bkb5mpLWsH4yx3P74aaXqy7wsozbzlYzDgp4LQFsokaZC11os4z5UJbp39EVIhtdODSNxYctD9dJDcq/oIU3R81Q9PzEhnp9EhLlwZp02NlyzQc5xpcaGF/PAQySj98ecZi5UjXZrZE9Ju2a6pvOEJRNRESEGJqL5hcQwls7gBQ=,iv:oODXL2FBjWmfa5Z37ljdf+Nd63XUZ9e/jC4keHoiQMI=,tag:Y2Jk0rU+QLEgv+S9vSX2qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
