apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: minio
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:fbvK5uw=,iv:Vp3EbUvbkKRTCIloMCm4d9dI/R+wNsAdKg2L3aUq5r8=,tag:XnmGPGFcspXvIduj1N0fQA==,type:str]
    rootPassword: ENC[AES256_GCM,data:IdFZDugRUJ93GvzluFfSwNbCO9PNZrbL/yynTCOyrTk=,iv:VVPE6xCDxoUzRnokD29D5TdiqX6zBJEyAo14aytSomM=,tag:riBIA+wbXCHWttZMptytRQ==,type:str]
    blogSecretKey: ENC[AES256_GCM,data:ksGYXKjVrnv7INNHFq05wC0M55R1EWviCmyiEHvtnTfr+ABlcRMchw==,iv:vkI/GNU8aT/XR468ghTfgrLGFZHGwYWkw/oAKfENWjU=,tag:BQUP0OC/0X2+mkbyjfqgIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK1BZR2FRTXhaN1ZUVzdR
            dFI4UGZicVhKSE1ZeGZqMnBnMjlBY0QrcUVvCnJWZ3pSNlFTVFNzdEVYQ0trL045
            T05iY2pjR2tjMmhxYm5IeUhYVFVhRDgKLS0tIDViL2M4bThzS3lsQnhJS2UzRVJL
            TWM3aGVhSlVMQ0RrVGtpbFJ1YXpLc2sK+AQhZmf/+D9xpnjh2BsBT4HR8eU6gvzY
            FR15dLHEfQ+R25u1z90g8H2hVidJUZPzW5NAziVT9HhLf3SsgGDqHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T22:40:34Z"
    mac: ENC[AES256_GCM,data:UHQYkoSoG8TCRm6zRaJ+oyi4oCSzrgmbKp1fHPTX20cUEEOiwI3f2rvRIZQ3TOlktT4I9PJGHG3Go+ivnz/ONufVidqLkhTHbeeQFtHi+K+rJJp/R8XKhF58zG3+LSW/XKZqPL2BDeCniM2+xpJxLFgLMpBJ/MHzbv/kOniq3bQ=,iv:0idjgcNesMPcvO9oevfHFgXUBqZAAnC5PJlC4iwdf7Q=,tag:5/0SXoV8zxxpLz/AZIy54Q==,type:str]
    version: 3.13.1
