apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: minio
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:ppIQHnMeLbLxrQ==,iv:dVplXqoVbEyRd4NhlfYgK9PB5+W31wo0sA0KfCQd4tQ=,tag:urZc2GYzsbXGMuBoJEFgpg==,type:str]
    rootPassword: ENC[AES256_GCM,data:IdFZDugRUJ93GvzluFfSwNbCO9PNZrbL/yynTCOyrTk=,iv:VVPE6xCDxoUzRnokD29D5TdiqX6zBJEyAo14aytSomM=,tag:riBIA+wbXCHWttZMptytRQ==,type:str]
    blogSecretKey: ENC[AES256_GCM,data:ksGYXKjVrnv7INNHFq05wC0M55R1EWviCmyiEHvtnTfr+ABlcRMchw==,iv:vkI/GNU8aT/XR468ghTfgrLGFZHGwYWkw/oAKfENWjU=,tag:BQUP0OC/0X2+mkbyjfqgIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK1BZR2FRTXhaN1ZUVzdR
            dFI4UGZicVhKSE1ZeGZqMnBnMjlBY0QrcUVvCnJWZ3pSNlFTVFNzdEVYQ0trL045
            T05iY2pjR2tjMmhxYm5IeUhYVFVhRDgKLS0tIDViL2M4bThzS3lsQnhJS2UzRVJL
            TWM3aGVhSlVMQ0RrVGtpbFJ1YXpLc2sK+AQhZmf/+D9xpnjh2BsBT4HR8eU6gvzY
            FR15dLHEfQ+R25u1z90g8H2hVidJUZPzW5NAziVT9HhLf3SsgGDqHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T22:07:45Z"
    mac: ENC[AES256_GCM,data:5C6B89JyMIid3yS4ZTPWbBnqNitTRXIoavlpXb8A7E9x5Pf0J46cqo8qLo0RhwArcqQz+AlM8IzWV8ivy9nRcGvLKnNHB7Jn2JSzOt1qXeLhCfYTmBSIn1si0j4yRjCA/te9S7ER7nEn/RgyKjiWNRuLBXt8TkXyqTxejD58KgE=,iv:MRpCkO63vNBbwAi4yoFe+8kegkvJ7gsfawBW6c4HIPA=,tag:19I4P8LIaJiciFuPj3p9wg==,type:str]
    version: 3.13.1
