apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:X5Yc/Cu6SuvtseaG0hrLAEOERXv4Iybp536UINsrTHGB/DEeqUSp4U0WycVeuMfO,iv:1GlkB28JHfus/CLvpq+mzrlL2DBZn9gBoCETyuGB0/s=,tag:luYpHz7Lym3jB6GIPeJlXA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:0kdpPS+EwNaP1rS96X8BAa2gwm5PJuU0PT+cL8lDacXVAtgzcHlY5LqJbJRsPEuPctd6FpCjmhyspVNYvZbLGQ==,iv:HwpRobMA4rcM4WUvcIwb+4peBlng31rv4PeUrcnlDho=,tag:PIKtWY9V4WiYaiEYfLFn9w==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:FgtUVz4=,iv:2MPRbryPiT+Q0z+dt4K00lPxwicloirQkVqxMPyllqE=,tag:SUuE8UtlPGgYYdCWR/VsQg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:N84LAD0sgVqetrdIyz8gKAC9xh2owKkrT+ymJha8BLg=,iv:X9uUAfuUepQTT3GPfRQ/N5QGizRADggQGPv2wI/Zh2c=,tag:l5d2lPy/4quBNzmAOe8qMA==,type:str]
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:V5eFyuhhaIcbWRzWchIzHl2wz2n08AD/6Pu0wSKJRFPW94M=,iv:qibHEHMjzS5ilcgbkEC8M0nuPDPvItHO2k+AG2OoTHc=,tag:Ab3BOzJJ9X39keLn0YID6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRm5OeHhVdE5KSkVzbVFS
            UDJSSUxBUlZjNFM2TFVVYlI4aktMcFFMMlFBClZodllLWk5qS3BsWGljbkg2ZGlr
            aVpYMk5Ia2tBTjQxTUpLck5jTDdJdGcKLS0tIC9ONCtJYWphUU5zT0xBL2dITHhO
            VEdtYmhrK3VsN2FBeU5LeDBrSEpjMGcKrYvuWfbDis/0eZeK2GK+p2Ld2ePqsmSe
            0fA3Yw6PX/HongDLWuydPofdBM4E345BPVFfYyENwOvvFV+Lkb+ufw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T14:14:10Z"
    mac: ENC[AES256_GCM,data:SQCYacp2Hlsf+9OFzNbhEUUiaXXWqIx7RufII6fMhHkF3PbsbCHL48KxlmTFn7LF/w5EMbi0M+qhKsYC0F2gfhm7zqseWlYmixAN3uWBL80jtjzPt7YmjwHaNI6UoXxWS4ktL9ua8sKe9YSvCD8AvPNkK7CGiCE/1TWA2MIxv28=,iv:7fotfbig7lRL1tbDyib9wqY3G0za5FKQOzoJ55X/Hug=,tag:ak0iJDLldU2umAgD1m6rWA==,type:str]
    version: 3.13.1
