apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:X5Yc/Cu6SuvtseaG0hrLAEOERXv4Iybp536UINsrTHGB/DEeqUSp4U0WycVeuMfO,iv:1GlkB28JHfus/CLvpq+mzrlL2DBZn9gBoCETyuGB0/s=,tag:luYpHz7Lym3jB6GIPeJlXA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:0kdpPS+EwNaP1rS96X8BAa2gwm5PJuU0PT+cL8lDacXVAtgzcHlY5LqJbJRsPEuPctd6FpCjmhyspVNYvZbLGQ==,iv:HwpRobMA4rcM4WUvcIwb+4peBlng31rv4PeUrcnlDho=,tag:PIKtWY9V4WiYaiEYfLFn9w==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:FgtUVz4=,iv:2MPRbryPiT+Q0z+dt4K00lPxwicloirQkVqxMPyllqE=,tag:SUuE8UtlPGgYYdCWR/VsQg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:N84LAD0sgVqetrdIyz8gKAC9xh2owKkrT+ymJha8BLg=,iv:X9uUAfuUepQTT3GPfRQ/N5QGizRADggQGPv2wI/Zh2c=,tag:l5d2lPy/4quBNzmAOe8qMA==,type:str]
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:xxuCJ401IK1rOIwJla1Yfsh7LQaAFMsh///jXjBhiWLUUnwX4JDWWA==,iv:MaLidQChqcjXm1S9W+jqPoKE6TaT4An/UHW9MNewMHk=,tag:EdItRzr+Dsg9xHKpT1DkLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRm5OeHhVdE5KSkVzbVFS
            UDJSSUxBUlZjNFM2TFVVYlI4aktMcFFMMlFBClZodllLWk5qS3BsWGljbkg2ZGlr
            aVpYMk5Ia2tBTjQxTUpLck5jTDdJdGcKLS0tIC9ONCtJYWphUU5zT0xBL2dITHhO
            VEdtYmhrK3VsN2FBeU5LeDBrSEpjMGcKrYvuWfbDis/0eZeK2GK+p2Ld2ePqsmSe
            0fA3Yw6PX/HongDLWuydPofdBM4E345BPVFfYyENwOvvFV+Lkb+ufw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T14:40:07Z"
    mac: ENC[AES256_GCM,data:go54ck0Q4GtfaysNOTbksLIVjk9c+A2qTtTVa8urln4T0mnxXNBylhYaGc6JBGxKwQQRBwIsQKqSjWDnzfBLMJbnDCodfSLwcixrP0tPpfhZRnNO/DdB29H/LF8R41OnMvrePOj35hQ2JTZkGn0gvZDopD0Iu47PaAaKZyQY4vA=,iv:5HDj+WzuvpYh3ePNFuu444jW9PVzhSHkV7Sdkb7euF0=,tag:6MMzqoTiG1NL9GPEzFAv/Q==,type:str]
    version: 3.13.1
