apiVersion: v1
kind: Secret
metadata:
    name: pg-authentik
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:CT+36bm/TW9/,iv:nMMfkKj191ribI/i59wK9enNGQfCtmNvZLBrDQUouCk=,tag:lXFJZq38aoAaJWT+v/1DzA==,type:str]
    password: ENC[AES256_GCM,data:i+Ii6+cQvECU2zJRleOUUDFYlgmoYXJgKtLhJmJc9KWB7BH9nsHrpw==,iv:J9YQAyRh6XvfKCD6HSETu+UV1WlI9rD8NeFz3tinXqI=,tag:fuDO5Vi7PtJGqT3YP+vmqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Q01TZVdzQmRSdW5BS1p3
            V3NoVDMrZEhLVTZVMUhidFlyNisrc2FXSVdnCko2TUNBaXlMdDFoU29XRHBNVy9l
            WXcrN2pycVRkbzN5dHBXQkhSazIvZEkKLS0tIEFXa1hBYitPdEZIUDJoTzZXQnh0
            ZHoxNXJhbzROUG91N0ZJelp0ZU43MnMK1A+TA7lPA61VYTFJVXHss1Gmvnueewep
            uwvHd5hko77VnNq3+/ZEPJaK4iR3jLXz6IBBLO7CUd942lEvw37dbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T20:15:29Z"
    mac: ENC[AES256_GCM,data:aiUnnZbVy3EGY7JEllX0usb89PcZ1jbA/7tDXNgBaSIZCt40ldlKG0O5NiAzxAfpCF+VZmEJPqNUB14fz91iNVWS6BIkpQSyUvvOTRwJ32b/Zm+6pAVpHHFufuU0pYovq10+Jk/I8VKLEcX/gun8fpzhtqz8npBDDWwbsO95XIs=,iv:5BccotcBornYjws8+M9kjaLlx6mLDcvk7JMaZQn57Hw=,tag:PamkcZa7WPh6kjVvneAsUA==,type:str]
    version: 3.13.1
