apiVersion: v1
kind: Secret
metadata:
    name: pg-litellm
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:s6cnSBanng==,iv:waRYiRHJV7pe6QCdP9PoBqBGwMfkJoZ5VyF/r2MXh/I=,tag:1iv36rFn97sP4nW5HUu72w==,type:str]
    password: ENC[AES256_GCM,data:1KOW4/w6cTqIAq3PQFRUKuNllvF45nTBhKvqRDpYRdFhimGqGvY6Iw==,iv:z1ouNLVA9ihG55hba/qjMhZjb+4YV8LY0Xk6RNpOopw=,tag:jArHXpftXIr74iFY7ipTMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UERubWltWlpteVJ6dVBU
            UHJYb3AxMVJrR2gxZzkwa1haSGltdmptRURvClQ2a0lpNVRJVmNCby92VUZORjRP
            b1QwSkhFL3gwVHJOZDROZmg5MDFiWEUKLS0tIHYxRFpQV3hrd0RaY2JCQ295M2ly
            N2RVNEhGN29nZ0ZKdlY5UWExZGFIRUUKUS3my+FhYFHfIhKOdrWqp9jEO8y621N7
            C8kSIuQ2JLm/m2B4+TZlVy0gQydIK1blQFaudIZ5ugOYFvxlPZUH8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T20:15:29Z"
    mac: ENC[AES256_GCM,data:JW5AtMrp7nZv3yB60fCrsdl5rOkyGzhI/5lZU33cNLSglzV+CqrfqAoF7qaemXUyog8WsDG3lhkLvynRw1s0UMYPk8l5O5kg8K2qa46/zYb3yIqi5ZJ3HmtK4T4g6al3etJdY06K+b7/WGvm6z/lQDz3xrIVik2jYNyi/L3JWc4=,iv:CRynZrEOiigDS4GGp3aUhI1PQeVHcakws1Ijxrbu1wU=,tag:Of2MohYfLz1yDQVjkZMfBQ==,type:str]
    version: 3.13.1
