apiVersion: v1
kind: Secret
metadata:
    name: pg-paperless
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Z/DJIpI8Rtnm,iv:0tlOT0W68AuUrQJNJN3JbcCmpDTNhnKjSPqx/NiVuyo=,tag:wxB87QuaTIr6GhEIiz5gZw==,type:str]
    password: ENC[AES256_GCM,data:vxNL1SKHiCAhxUMz3CIHu5toD/pyKHo4IGD25owW8mZ+mmu/Gjn4LelyjX1aTEY1,iv:pBfQtexkmdmAnX7b3t/LrKGkwd/+BG2kfyiDIcS1aFM=,tag:LslDbppFnRXoL5TSQvqnaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVkFDMzV1RGhSVENqV2VQ
            UEFOSmNFcmwzVVV4U1RBNW0vVG15S2JaalNRCmVjUHgxcXZ6b1BVZHBRQ2dMdFZM
            ZmxraFozUlZzN2VQenFwaXhJTG5uRDQKLS0tIDdZOGVEY095YUFxLzcvRm8zenZv
            b0R4eXdIeXgvSE11TFljL3dKdXlqUkEKAidHk+TAJnx34tyH3EaDOZDFoqWx27t+
            ZIsdO8PaDDQZrfuwTJvvwsLsw2suHA7IFYQmKVw3G4qm6GgQfHthNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T14:14:10Z"
    mac: ENC[AES256_GCM,data:X1Wj1n68Ms7ZBREx/f+0RI4ec8s/R5j8CVVEDD/b3sehNZQCOQJrldygpi+spnaXSRIgKyCr8m6HVXcpnhEy9GMDMjBw+ukoIeSrJWd//mfiyOZ/nssrBjfw4A3xE7pGLvB0m9iT8kpSaJ8iH4xGvnOhHqBGzY/SKBXA+qZC7TM=,iv:76NJYT1XJT/kg0hvoqwGHNRLphpxc+iwtnJI3UhaRFA=,tag:7rASLiWQa9/ykouTjeDcag==,type:str]
    version: 3.13.1
