apiVersion: v1
kind: Secret
metadata:
    name: rancher-admin-secret
    namespace: cattle-system
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:svxc4k8XhefCfiR79w==,iv:66/8qfxVkOYTz9IRIP7C1AwyF7y4FPSIq7MXhv3pinM=,tag:0+Lo6UAclCVC0yOdG/6WMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWkZmZ2w4NkdFWFRGOGJE
            eFBlSzI4cXBEa2dvSFRxYnJsTVRFTkFqeFdJCno4VTQ3R2tQaDJ4KzJwMytxS3ov
            a3VVWlhzSHM5THI5cFBFb2ZJbVh2WjQKLS0tIDc0aFhVQUJKUUN1cU9aUG1FN21K
            aU5JVGVTci9WQ1ljNlJ3eVMyUEZxeFkKhDQtHgOO1kTynogr74DLlpO5edNKbrzT
            SiUciGfGUzuJ/UaZxuMiznHatjl0LnOn8oE385rSWqO0o3Cievt/5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T23:56:01Z"
    mac: ENC[AES256_GCM,data:4Sk5POPOErkP+PlsVtCWsCzZ/lacpLWGJBChmcthFv2QYlT9nVVnbqLTJhN4ZC+XKPDZTWjUFOYM0zjTW6PQOLYJGm5fbdrGHqPSkVFXBeNBK/nYtlE+z6W47QFjZRoZnDcxV5vOaGa8B65SAF9W5gh0TdVE5hecUqvcqS4aS58=,iv:40LnXRujDQeX3Fh7fPIFiUTn3bJyS3YD864c98qi6l4=,tag:Guma5tGfAu/HXkta4DfL5Q==,type:str]
    version: 3.12.2
