apiVersion: v1
kind: Secret
metadata:
    name: velero-repo-credentials
    namespace: velero
type: Opaque
stringData:
    repository-password: ENC[AES256_GCM,data:fojHQtfX/OiiWdb4haSh,iv:zWPE+PC2pSR+Un8o6nY83n+N+RkTXeQ4dQwc0FnYDAk=,tag:Phhm+Ni+pIR2MSpgMCuxwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbkMvNEloaWpnemdyZlZu
            dW1JVFJyRi9XQ1dFZmhnRlpIQkJlaUhYdFcwClViZWRwVEkyb1BKUHFvSXFXYmQ0
            QXpFaC93VUZKSHVvemRZNVFUSDlYTFkKLS0tIDdMeGI0c0grRVBOSDNDNnR5SDZU
            N1Y1V1FRclhYeHB2TEhwblZrWk9DZ2cKQoGxaTk6PgxyCBpXXJqxpQvHUd1Yj7g/
            C0TxkrT0gHpD/B2ov2MHZjyU2hJahi71+2kpZ4ovPtsiumyqkF1eyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T21:06:23Z"
    mac: ENC[AES256_GCM,data:t+mjDwgP/A9bc+LCDLZucj6R20RS2HRRietj6LorZg8QmKoZ2lzK9GQV9aBYJ12eXpFsAbUGl2j0au9Jm/ZRlEjz5Zp3BRBcBNauQ5poL6JaKk/ols39X4culwe/0RZmZiRyD8WpYZG9hqao6vCsn9mAMIm+s/QFx8C4uVW28Cw=,iv:PwqMI1r1K4nwY2lZDTfRfrKnNbYqZunyz0J28WvJnaw=,tag:/htwIa8DrHA7v9KiouxpPQ==,type:str]
    version: 3.13.1
