apiVersion: v1
kind: Secret
metadata:
    name: velero-s3-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:yq2A+vsmNb++MXdzH29sSi7bQYdcueFKfTmYdy1QuCjajWd2mu3SlIgBCSibJikKIjB1/2i+bmYBjIchirlgbHayR+m7be7B13Qw+9WoV1AcwG8aqnyHCqIDr/U4e3A0/nYTrxu40epkSuRpe/68qQ==,iv:qjKHEtRRORp950bWAxPK7QIrUQEQY2w2H4fPq2+ae2c=,tag:YDFMak7JWA6rrEk2ayji3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSE9ZTElaNlVpcGpTSmRF
            S1ZjTHJ1SWVXa3FMVUxjZ1F2SVMwK1RMOG1BCnhDbEhKeEI2eDdiTE1HRFdRTStm
            K29pajdqZWZyLytLOGlnYWx1ZFBtOXcKLS0tIE9Rb25VKzE3YzlMMWpqVkM4WkQ0
            V0RPMjhZWHZ6ZEUzRm9YU2M1M2hub0kK51JKm+qufGDJrzkGqJ5hyNxF5iKWJ1p7
            uo7wzs7pso62Fdk/GiO4I6J4aY9xSKxQwf0YHoCZhh9il5urFp0yXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T20:51:22Z"
    mac: ENC[AES256_GCM,data:IViAz2Sxbwcz4Xxvh0wB2pWOrijU5AYJ5w4IBMJ9esnFiCYwQrfvlNjzptn2n3U+hZtxlOJY0YC+rRkM7NimXv4+TExIe5K3sV6J2M/E0/wGnP1ya55YGXrhrM04BtRAoGnB1otT2B+PEHpR4O+XDRH7RSQWNg9DEh3potyHBoQ=,iv:3PFKnj62ZplpKowVAs+Se49nHlIcdJssx08qJldr47U=,tag:Il0GS7fBeyKg1fPMrJsLBg==,type:str]
    version: 3.13.1
