apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - paperless-ngx
  - redis
  - gotenberg
  - tika
  - paperless-ai
  - paperless-gpt
  - ingress.yaml
  - networkpolicies.yaml
