apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: gitops-peer-flux
  namespace: capa-system
spec:
  clusterSelector:
    matchLabels:
      bedrock.io/gitops-peer: "true"
  strategy: ApplyOnce
  resources:
    - kind: ConfigMap
      name: gitops-peer-flux-components
    - kind: ConfigMap
      name: gitops-peer-flux-sync
