apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: authentik
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:lhA9lwY1iOQk0yTyLvxQytXYQDoYSkMZbrm0pNw+xMfgOhl0j8otNOJth5RCkBG+UUGANDvBIzOE52S4,iv:WwgaHY8354xVSlnNN1U4lgvhmnjYapY7uaM8ulzVa4s=,tag:aekrpVaTpqvMq/z+P5eATg==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:saYGU/Tetf6x7sJxtKAFgn9I6+FF2XTv55sAdaTLffo=,iv:g4IcYdbfQWR2v50hv2B2xicJxAkTr6E8xiqpBHBBizM=,tag:iqyqtdI8HVo0m/DsdAqKGQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:fxt6Gh+x5fDY/6b5Jd0/uGLu1z8KzC+gWPMMp3n8jWv84kowTmiEzw==,iv:ANh+nv/ti2KmZrVd358Zkka3ILyn5VQSYGPkYh4N9FY=,tag:8+Su+apc8kiSJ/VBucEGQw==,type:str]
    github-client-id: ENC[AES256_GCM,data:6E1m9ag79ioF66Czhf3Uv6RW6Ug=,iv:oNuqGZcE+0AfTQiW6BgLdlIzuKOS+1MHCKSArZTIo5E=,tag:0VjbvkiBrDSVf7TH4ZeiHQ==,type:str]
    github-client-secret: ENC[AES256_GCM,data:JW6aUmZQ1xWaf+9uViA6inBFK/TO1wMzkG9qdZY8lzhraUoiV+2JGA==,iv:xB/xu5X0Js7F10AfzxzsfZ5XOrpJYz0zFd2+NV0UWh4=,tag:6JXszVmHZ2x6al2qFmxfPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeTlKSVlSZHZuSm9TSlVM
            dndQbUc4MEpyR2FoTUlDQ0NiUHNLeEViSldRCk4zQWljZzZzUmw5cG95T2dCa1BE
            M3JIZXF1aUtVV1hVaElzZnVFbjRXWGMKLS0tIDZwWDRqWk0vdnZRMWlET3NiUjdy
            V0JyM250V3NhK1phRTFvMlRoK0dTUGcKDrdtIaeX2aZ220hOr7wBsbdOvwhQ2w0q
            awHSqBXgMy4KqiuqSlW7YcgVtQXqG3y3c/7LOrYYFU2qat0GF8xQug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t3ce6qjhjffvdamzmdhp50tnfnkyw0ytmzkw0s844vfdmystcp2qfvdem9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T20:19:03Z"
    mac: ENC[AES256_GCM,data:iSO5hoh6yPgewHTLglSUSU6MEUuuQUvrYMtFhqk7SdyIjxDLV0ijDVOCRUTxF/utapY30zjrHurpnVvcq0RdvCt0rRAz6C0upw/LMkeGeS4pwvJB7+M4RxZXwr+zebj4CE5tSgvXGiKNMgsw0ul7OwgwIaggU+ymTBUk17L+CU8=,iv:3t1+L6yvVYPJR8sjvuOn22a5DFCKAlRGLLTRLYg8Y9w=,tag:ifcPnBcf4r6nCvHRjAj5SA==,type:str]
    version: 3.13.1
