apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: litellm
  namespace: llm
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: LiteLLM
    gethomepage.dev/group: AI
    gethomepage.dev/icon: sh-litellm.png
    gethomepage.dev/href: https://llm.syslabs.dev
    gethomepage.dev/podSelector: app.kubernetes.io/name=litellm
    gethomepage.dev/statusStyle: "dot"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`llm.syslabs.dev`)
      kind: Rule
      middlewares:
        - name: litellm-root-redirect
      services:
        - name: litellm
          port: 4000
  tls: {}
