apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: litellm
  namespace: llm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: litellm
      app.kubernetes.io/name: litellm
