apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
components:
  - ../../../components/network-policies/base
  - ../../../components/network-policies/traefik-ingress
  - ../../../components/network-policies/internet-egress
resources:
  - helmrelease.yaml
  - networkpolicies.yaml
  - ingress.yaml
  - pdb.yaml
  - pvc.yaml
