apiVersion: controlplane.horizon.dev/v1alpha1
kind: ExternalControlPlane
metadata:
  name: burst
  namespace: caph-system
spec:
  controlPlaneEndpoint:
    host: 10.20.0.10
    port: 6443
  version: v1.35.2+k3s1
