apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
components:
  - ../../../components/network-policies/base
resources:
  - helmrelease.yaml
  - networkpolicies.yaml
  - pdb.yaml
