#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
clusters="$repo_root/kubernetes/clusters/home"
out="$repo_root/docs/inventory.md"

rows=""
while IFS= read -r f; do
  row="$(yq -r '[.metadata.name, .metadata.namespace, .spec.chart.spec.chart, .spec.chart.spec.version] | join("\t")' "$f")"
  rows="$rows$row"$'\n'
done < <(find "$clusters/apps" "$clusters/infrastructure" -name helmrelease.yaml | sort)

sorted="$(printf '%s' "$rows" | LC_ALL=C sort)"

{
  echo "# Cluster inventory"
  echo
  echo "Generated by scripts/gen-inventory.sh from the home cluster HelmReleases. CI regenerates this on merge to main; do not edit this table by hand."
  echo
  echo "| Component | Namespace | Chart | Version |"
  echo "| --- | --- | --- | --- |"
  printf '%s' "$sorted" | while IFS=$'\t' read -r name ns chart version; do
    echo "| $name | $ns | $chart | $version |"
  done
} > "$out"
