#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$repo_root/docs/inventory.md"

rows=""
while IFS= read -r f; do
  row="$(yq -r '[.metadata.name, .metadata.namespace, .spec.chart.spec.chart] | join("\t")' "$f")"
  rows="$rows$row"$'\n'
done < <(find "$repo_root/kubernetes" -name helmrelease.yaml | sort)

sorted="$(printf '%s' "$rows" | LC_ALL=C sort)"

{
  echo "# Cluster inventory"
  echo
  echo "Generated by scripts/gen-inventory.sh from the home cluster HelmReleases. Re-run the script to update; do not edit this table by hand."
  echo
  echo "| Component | Namespace | Chart |"
  echo "| --- | --- | --- |"
  printf '%s\n' "$sorted" | while IFS=$'\t' read -r name ns chart; do
    echo "| $name | $ns | $chart |"
  done
} > "$out"
