apiVersion: cluster.x-k8s.io/v1beta2
kind: ClusterClass
metadata:
  name: default
  namespace: caph-system
spec:
  controlPlane:
    templateRef:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: KThreesControlPlaneTemplate
      name: default-control-plane
    machineInfrastructure:
      templateRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: default-control-plane
    naming:
      template: "{{ .cluster.name }}-master"
  infrastructure:
    templateRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: HetznerClusterTemplate
      name: default-cluster
  workers:
    machineDeployments:
      - class: default-worker
        bootstrap:
          templateRef:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
            kind: KThreesConfigTemplate
            name: default-worker
        infrastructure:
          templateRef:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HCloudMachineTemplate
            name: default-worker
        naming:
          template: "{{ .cluster.name }}-worker"
  variables:
    - name: region
      required: false
      schema:
        openAPIV3Schema:
          type: string
          default: hel1
    - name: controlPlaneMachineType
      required: false
      schema:
        openAPIV3Schema:
          type: string
          default: cpx22
    - name: workerMachineType
      required: false
      schema:
        openAPIV3Schema:
          type: string
          default: cpx22
    - name: image
      required: false
      schema:
        openAPIV3Schema:
          type: string
          default: bedrock-cluster-node
  patches:
    - name: region
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HetznerClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: replace
              path: /spec/template/spec/controlPlaneRegions
              valueFrom:
                template: |
                  - {{ .region }}
            - op: replace
              path: /spec/template/spec/controlPlaneLoadBalancer/region
              valueFrom:
                variable: region
    - name: controlPlaneMachineType
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HCloudMachineTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: replace
              path: /spec/template/spec/type
              valueFrom:
                variable: controlPlaneMachineType
            - op: replace
              path: /spec/template/spec/imageName
              valueFrom:
                variable: image
    - name: workerMachineType
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HCloudMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
          jsonPatches:
            - op: replace
              path: /spec/template/spec/type
              valueFrom:
                variable: workerMachineType
            - op: replace
              path: /spec/template/spec/imageName
              valueFrom:
                variable: image
