apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerClusterTemplate
metadata:
  name: default-cluster
  namespace: caph-system
spec:
  template:
    spec:
      controlPlaneRegions:
        - hel1
      controlPlaneLoadBalancer:
        enabled: true
        type: lb11
        region: hel1
      hcloudNetwork:
        enabled: true
        cidrBlock: 10.0.0.0/16
        subnetCidrBlock: 10.0.0.0/24
        networkZone: eu-central
      hetznerSecretRef:
        name: hetzner
        key:
          hcloudToken: hcloud-token
      sshKeys:
        hcloud:
          - name: bedrock-capi
