apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: open-webui
  namespace: llm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: open-webui
      app.kubernetes.io/instance: open-webui
