apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cloudflare-tunnel
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/service: cloudflared
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
