apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: horizon
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - horizon-system
  selector:
    matchLabels:
      app.kubernetes.io/name: horizon
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
