apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: headlamp
      version: "0.43.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    config:
      inCluster: true
      unsafeUseServiceAccountToken: true
    serviceAccount:
      create: false
      name: headlamp
    clusterRoleBinding:
      create: false
    service:
      port: 80
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
