apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kthreesconfigtemplate.yaml
  - cluster.yaml
  - hetznercluster.yaml
  - hcloudmachinetemplate.yaml
  - machinedeployment.yaml
