apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: burst-workers
  namespace: caph-system
  labels:
    horizon.dev/managed-by: horizon
    horizon.dev/pool-name: burst-workers
spec:
  clusterName: burst
  replicas: 0
  selector:
    matchLabels:
      horizon.dev/managed-by: horizon
      horizon.dev/pool-name: burst-workers
  template:
    metadata:
      labels:
        horizon.dev/managed-by: horizon
        horizon.dev/pool-name: burst-workers
    spec:
      clusterName: burst
      version: v1.35.2+k3s1
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KThreesConfigTemplate
          name: burst
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: HCloudMachineTemplate
        name: burst-workers
