apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Longhorn
    gethomepage.dev/group: Platform
    gethomepage.dev/icon: longhorn.png
    gethomepage.dev/href: https://longhorn.syslabs.dev
    gethomepage.dev/podSelector: app=longhorn-ui
    gethomepage.dev/statusStyle: "dot"
spec:
  ingressClassName: traefik
  rules:
    - host: longhorn.syslabs.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
