apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: postgres
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: pgadmin4
      version: "1.65.0"
      sourceRef:
        kind: HelmRepository
        name: pgadmin
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    networkPolicy:
      enabled: false
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false
    existingSecret: pgadmin-admin-secret
    secretKeys:
      pgadminPasswordKey: password
    env:
      email: admin@syslabs.dev
    persistentVolume:
      enabled: true
      size: 10Gi
      storageClass: longhorn
    serverDefinitions:
      enabled: true
      servers:
        homelab:
          Name: "homelab"
          Group: "Servers"
          Host: "postgres-rw.postgres.svc.cluster.local"
          Port: 5432
          MaintenanceDB: "postgres"
          Username: "postgres"
          SSLMode: "prefer"
    strategy:
      type: Recreate
    securityContext:
      runAsNonRoot: true
      runAsUser: 5050
      runAsGroup: 5050
      fsGroup: 5050
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      enabled: true
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
