apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: velero
  chart:
    spec:
      chart: velero
      version: "12.0.3"
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  install:
    createNamespace: false
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    objectStorage:
      bucket: &bucket horizon-velero-backups
      region: &region eu-central-1
      s3Url: &s3Url https://fsn1.your-objectstorage.com
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.14.2
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      features: "EnableCSI"
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: *bucket
          prefix: velero
          config:
            region: *region
            s3ForcePathStyle: "true"
            s3Url: *s3Url
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: *region
    credentials:
      useSecret: true
      existingSecret: velero-s3-credentials
    deployNodeAgent: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
