apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config-seed
  namespace: home-assistant
data:
  configuration.yaml: |
    default_config:

    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
  automations.yaml: |
    []
  scripts.yaml: ""
  scenes.yaml: ""
  http: |
    {
      "version": 2,
      "minor_version": 2,
      "key": "http",
      "data": {
        "stable": {
          "server_port": 8123,
          "use_x_forwarded_for": true,
          "trusted_proxies": [
            "10.42.0.0/16"
          ],
          "ip_ban_enabled": true,
          "login_attempts_threshold": -1,
          "cors_allowed_origins": [
            "https://cast.home-assistant.io"
          ],
          "ssl_profile": "modern",
          "use_x_frame_options": true,
          "error": null,
          "error_message": null
        },
        "yaml_migration_done": true
      }
    }
