apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hcloud-csi
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: hcloud-csi
      version: "2.13.0"
      sourceRef:
        kind: HelmRepository
        name: hetzner
        namespace: flux-system
  values:
    controller:
      hcloudToken:
        existingSecret:
          name: hcloud
          key: token
    storageClasses:
      - name: hcloud-volumes
        defaultStorageClass: true
        reclaimPolicy: Delete
