apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
    traefik: true

  settings.yaml: |
    title: syslabs
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      AI:
        style: row
        columns: 2
      Apps:
        style: row
        columns: 2
      Platform:
        style: row
        columns: 2

  docker.yaml: ""

  custom.css: ""

  custom.js: ""

  bookmarks.yaml: |
    - Cluster:
        - Rancher:
            - abbr: RA
              href: https://rancher.syslabs.dev
        - Grafana:
            - abbr: GR
              href: https://grafana.syslabs.dev

  services.yaml: |
    []

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: cluster
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    - prometheus:
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
